FROM eclipse-temurin:21
LABEL maintainer="Gruppe2-SPAM"
COPY target/choose-your-fate-backend-0.0.1-SNAPSHOT.jar choose-your-fate-backend-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","choose-your-fate-backend-0.0.1-SNAPSHOT.jar"]